### ISSUE TITLE
Project file is incomplete. Expected imports are missing

### ISSUE THREAD

**Issue by wvmstr** [AnkitSharma-007/Blazor-Server-Side-SPA#2]
When opening the sln for the first time:

ServerSide.App.csproj: error Project file is incomplete. expected import are missing.

**Comment by wvmstr** [comment]
From the command prompt: dotnet --list-sdks

Then edit global.json to use the version you want.

**Comment by biradarsm** [comment]
After changing the global.json, I am getting this error 
rzc generate exited with code 1

**Comment by AnkitSharma-007** [comment]
The code has been updated to ``` .NET Core 3.2 Preview-1```. Please try again and let me know if you have any further issues.
