### ISSUE TITLE
Problems with connecting to my db from sample

### ISSUE THREAD

**Issue by wvmstr** [AnkitSharma-007/Blazor-Server-Side-SPA#3]
Not having much luck connecting to my db I created to with the sample from github.
My new db has the two tables as per the tutorial.

This is what I did:
1. deleted the Models folder and it 3 classes
2. from the package manager: Scaffold-DbContext "Server=S4000W\SQLSERVER;Database=BLZR;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Tables Employee, Cities

It says Build failed

**Comment by AnkitSharma-007** [comment]
The code has been updated to ``` .NET Core 3.2 Preview-1```. Please try again and let me know if you have any further issues.
