### ISSUE TITLE
This Sample No Longer Works

### ISSUE THREAD

**Issue by MelbourneDeveloper** [AnkitSharma-007/Blazor-Server-Side-SPA#5]
When I try to open the projects in Visual Studio 2019, this is what I get:

![image](https://user-images.githubusercontent.com/16697547/73149779-001a5380-4117-11ea-831c-5e5a2007b05c.png)

I have .NET Core 3.1 installed and can use it for other projects.

**Comment by AnkitSharma-007** [comment]
The code has been updated to ``` .NET Core 3.2 Preview-1```. Please try again and let me know if you have any further issues.
